name = "Leiden"
uuid = "f7251f11-3029-455f-9099-70cf2221a549"
version = "0.1.0"
authors = ["Christian Degnbol Madsen <christian.degnbol@gmail.com>"]

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
CxxWrap = "0.17.4"
Pkg = "1.12.0"
